### ISSUE TITLE
Jog buttons are very slow to react

### ISSUE THREAD

**Issue by twforeman** [zapmaker/GrblHoming#2]
I downloaded and built this last night. It looks great, but when I use the jog buttons it's very slow to react.

I click the button, a second later the machine moves, then after another second the jog buttons un-grey and I can do it again. This is pretty much unusable for setting up.

I built it and used it under Linux Mint 14 and GRBL v0.8c.

**Comment by zapmaker** [comment]
The jog buttons are slow because they will only let you do one jog action at a time to prevent you from unintentionally stacking too many jogs and going right into the base (for those without limit switches).

But, you do have a good point and I will add this request to my to-do list

There should be no noticeable delay between clicking and seeing movement, so not sure what is happening, will look into that also.

**Comment by zapmaker** [comment]
Fixed in 3.4. I've commented out the code that waits for a response before reenabling the jog buttons. With it disabled it is possible to overstack jog commands and overflow grbl's limited buffer, so use with caution. Hopefully I'll get around to fixing that issue sometime.

I've also added a jog slider for the z axis to speed up z positioning (with the natural danger of sending the z axis beyond limits - be ready with the emergency stop button!)
